'deneme'
Hypance/HypanceFrontend pull request #3
Opened 2022-09-17 19:42 UTC by Berkan-Bilgin

2022-09-24 18:00 UTC, llnallna requested changes
denemeee

2022-09-30 16:45 UTC, Berkan-Bilgin commented on Sign-Up/README.md
> +
burayı düzelt

2022-09-30 16:46 UTC, llnallna requested changes

2022-09-30 16:46 UTC, llnallna commented on Sign-Up/README.md
> +
bu da 2. denememiz

2022-09-30 16:46 UTC, llnallna commented on Sign-Up/README.md
> +
eafd<gsdhgdfh

2022-09-30 16:52 UTC, Berkan-Bilgin commented on Sign-Up/README.md
> +
yapıldı

2022-09-30 16:54 UTC, Berkan-Bilgin commented on Sign-Up/README.md
> +
yapıldı

2022-10-01 19:12 UTC, BerkTenk approved these changes
Eline sağlık.

2022-11-28 19:22 UTC, closed without merging