route initialized
Hypance/HypanceFrontend pull request #9
Opened 2022-10-02 19:50 UTC by aslannburrcu

2022-10-02 19:52 UTC, llnallna approved these changes

2022-10-02 19:56 UTC, llnallna requested changes
src altında Components klasörü açıp o klasörün altında her componentin kendi adıyla yeni klasör açalım.

2022-10-02 20:07 UTC, llnallna requested changes
Pages Klasörü ve içeriği tamamen kaldırılabilir.

2022-10-05 17:02 UTC, aslannburrcu commented
Pages sayfası silindi.Components dosyası oluşturuldu ve altına önceden isimlendirilen dosyaları oluşturuldu.

2022-10-07 21:45 UTC, merged